name: Push protocol buffer package

on:
  push:
    branches:
      - "dev"
      - "master"

jobs:
  push_pb:
    strategy:
      matrix:
        os: ["ubuntu-16.04"]
        go: ["1.14"]
        node: ["14"]

    runs-on: ${{ matrix.os }}

    steps:
      ##
      # Install
      ##

      - name: Upgrade OS
        run: sudo apt update && sudo apt install -y ca-certificates openssl git tree
        shell: bash

      - name: Install Go & gogo/protobuf
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - run: |
          export GO111MODULE=off
          go get -u github.com/gogo/protobuf/proto github.com/gogo/protobuf/protoc-gen-gofast github.com/gogo/protobuf/gogoproto

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      ##
      # Build
      ##

      - uses: actions/checkout@v2

      - name: Define package name
        run: echo ::set-env name=PB_PACKAGE_NAME::${GITHUB_REPOSITORY#*/}@${GITHUB_REF##*/}
        shell: bash
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"

      - name: Make package boiler plate
        run: |
          mkdir -p ${PB_PACKAGE_NAME}/proto &&
          mkdir ${PB_PACKAGE_NAME}/go &&
          mkdir ${PB_PACKAGE_NAME}/grpc-node

      - name: Copy proto files
        run: cp -rf **/**/*.proto ${PB_PACKAGE_NAME}/proto

      - name: Build PBs
        shell: bash
        run: |
          ##
          # Setup Golang deps
          ## 
          GOPATH=$(go env GOPATH)
          GOBIN=$GOPATH/bin
          PATH=$PATH:/usr/local/go/bin
          PATH=$PATH:$GOPATH:$GOBIN

          ##
          # Setup Node deps
          ## 
          npm init -y
          npm i ts-protoc-gen grpc-tools
          NPM_BIN_PATH=$(pwd)/node_modules/.bin

          ##
          # Build Golang PBs
          ##
          cd ${PB_PACKAGE_NAME}/proto
          for file_name in *.proto; do
            protoc -I=. -I=${GOPATH}/src -I=${GOPATH}/src/github.com/gogo/protobuf/protobuf\
             --gofast_out=plugins=grpc:../go "./$file_name"
          done

          cd ../../
          pwd
          ##
          # Build grpc-node PBs
          ##
          GRPC_NODE_OUT_DIR="${PB_PACKAGE_NAME}/grpc-node"
          protoc -I=. -I=${GOPATH}/src -I=${GOPATH}/src/github.com/gogo/protobuf/protobuf\
           --plugin="protoc-gen-ts=${NPM_BIN_PATH}/protoc-gen-ts"\
           --plugin="protoc-gen-grpc=${NPM_BIN_PATH}/grpc_tools_node_protoc_plugin"\
           --js_out="import_style=commonjs,binary:${GRPC_NODE_OUT_DIR}"\
           --ts_out="service=grpc-node:${GRPC_NODE_OUT_DIR}"\
           --grpc_out="${GRPC_NODE_OUT_DIR}"\
            **/*pb/*.proto

      - run: tree ${PB_PACKAGE_NAME}

      ##
      # Push
      ##

      - name: Push ${{ env.PB_PACKAGE_NAME }} to share-proto-repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.HOORY_COM_ACCESS_TOKEN }}
        with:
          source-directory: ${{ env.PB_PACKAGE_NAME }}
          destination-github-username: ${{ github.repository_owner }}
          user-email: ${{ github.actor }}
          target-branch: ${{ env.PB_PACKAGE_NAME}}
          destination-repository-name: share-proto-repo
